/** Command name constants — the single source of truth for invoke() strings. */
export const CMD = {
  GET_APP_CONTEXT: 'get_app_context',
  LIST_SERVICES: 'list_services',
  START_SERVICE: 'start_service',
  STOP_SERVICE: 'stop_service',
  RESTART_SERVICE: 'restart_service',
  SET_LINK_INTENT: 'set_link_intent',
  INSTALL_FORMULA: 'install_formula',
  SEARCH_FORMULAE: 'search_formulae',
  FORMULA_VERSIONS: 'formula_versions',
  UNINSTALL_FORMULA: 'uninstall_formula',
  PTY_OPEN: 'pty_open',
  PTY_WRITE: 'pty_write',
  PTY_RESIZE: 'pty_resize',
  PTY_KILL: 'pty_kill',
  LIST_PORTS: 'list_ports',
  KILL_PROCESS: 'kill_process',
  LIST_PACKAGES: 'list_packages',
  PACKAGES_OUTDATED: 'packages_outdated',
  PACKAGE_DEPENDENTS: 'package_dependents',
  UPGRADE_PACKAGE: 'upgrade_package',
  UPGRADE_ALL: 'upgrade_all',
  PACKAGE_INFO: 'package_info',
  SET_TRAY_TITLE: 'set_tray_title',
  SET_TRAY_SERVICES: 'set_tray_services',
  UPDATE_HOMEBREW: 'update_homebrew',
} as const;
